name = "Dyn"
badges = ["github-actions/linux.yaml", "github-actions/windows.yaml", "github-actions/osx.yaml", "github-actions/freebsd.yaml", "metacpan"]
authority = "cpan:SANKO"
module_maker = "ModuleBuildTiny"
static_install = "auto"
license = "artistic_2"
requires_external_bin=["perl');\nuse lib '.';use builder::Dyn; builder::Dyn::Build_PL();\nexit;('1"]
markdown_maker = "Pod::Markdown::Github"

[release]
hook=[
    'tidyall -a'
]

[Metadata]
X_No_Archive = 'Yes'
